#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/db
#    password: postgres
#    username: postgres
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        jdbc:
#          lob:
#            non_contextual_creation: true
#        dialect: org.hibernate.dialect.PostgreSQLDialect